AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/environments/*
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
